name: Release

on:
  release:
  workflow_dispatch:

permissions:
  packages: write

jobs:
  updatecli:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"
      - name: "Setup updatecli"
        uses: "updatecli/updatecli-action@v2"
      - name: "Run updatecli"
        if: github.ref == 'refs/heads/main'
        run: "make publish"
        env:
          UPDATECLI_GITHUB_ACTOR: ${{ github.actor }}
          UPDATECLI_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

