name: Release

on:
  release:
  workflow_dispatch:

permissions:
  packages: write

jobs:
  updatecli:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"
      - name: "Setup Updatecli"
        uses: "updatecli/updatecli-action@v2"
      - name: "Run release"
        run: "make publish"
        env:
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

