name: Test

on:
  workflow_dispatch:
  pull_request:
  push:
  schedule:
  # * is a special character in YAML so you have to quote this string
  # Run at 12:00 on Friday.”
  - cron: '0 12 * * 5'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"

      - name: "Setup Updatecli"
        uses: "updatecli/updatecli-action@v2"

      - name: Login to GitHub Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: "Run test"
        run: "make test"
        env:
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

